### ISSUE TITLE
Stream support

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/workshopper-adventure#3]
Right now the output doesn't support streams like adventure does optionally - only text processing supported - Needs some rather substantial rewrite for this.

**Comment by tgfjt** [comment]
I want to try to support this, but I don't have enough time on May so I will set about this on next month.

**Comment by martinheidegger** [comment]
I have taken some time to put stream support in the https://github.com/workshopper/workshopper-adventure/pull/2 branch @tgfjt Do you mind reading through the code?

**Comment by tgfjt** [comment]
No, I will read.:D
Could you wait a couple of days?

**Comment by martinheidegger** [comment]
No problem

**Comment by tgfjt** [comment]
@martinheidegger 
Give me couple more days please, because I've been busy these days :crying_cat_face:

**Comment by tgfjt** [comment]
@martinheidegger 

I've tried on https://github.com/tgfjt/test-anything/tree/workshopper-adventure, only update workshopper-adventure,

``` diff
-    "workshopper-adventure": "^3.4.1",
+    "workshopper-adventure": "git://github.com/workshopper/workshopper-adventure#f2762f8",
```

but first, I got this error when I run `./test-anything.js`. Do you know how to fix? :sweat_drops: 

```
TypeError: Object #<Adventure> has no method '__'
    at Adventure.add (/Users/tgfjt/workspace/nodeschool/test-anything/node_modules/workshopper-adventure/adventure.js:170:25)
    at Adventure.<anonymous> (/Users/tgfjt/workspace/nodeschool/test-anything/node_modules/workshopper-adventure/adventure.js:96:12)
    at Array.forEach (native)
    at new Adventure (/Users/tgfjt/workspace/nodeschool/test-anything/node_modules/workshopper-adventure/adventure.js:95:23)
    at Adventure (/Users/tgfjt/workspace/nodeschool/test-anything/node_modules/workshopper-adventure/adventure.js:32:12)
    at Object.<anonymous> (/Users/tgfjt/workspace/nodeschool/test-anything/test-anything.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by martinheidegger** [comment]
I pushed a fix to the refactoring branch. Thanks for testing it. Btw. I found a small bug that occurs in io.js >= 1.3.0 : go to "change language" then "cancel" the "select entry" :-(

**Comment by tgfjt** [comment]
@martinheidegger  I'm glad that you got better. :smile: 
Sorry for no-response because I'm really busy now.
Let me have more a little time please!

**Comment by martinheidegger** [comment]
Should work with https://github.com/tgfjt/test-anything/pull/1. Closing this issue:
